# Site settings
title: Kevin Plattret
email: kevin@plattret.me
description:
baseurl:
url: https://kevinplattret.me
root_domain: kevinplattret.me
ga_tracking_id: UA-26055002-2
twitter_username: kplattret
github_username:  kplattret

# Build settings
markdown: kramdown
exclude:
  - README.md
  - LICENCE.md
  - CNAME
  - assets/css/main.scss
permalink: /post/:title

# Plugin settings
gems:
  - jekyll-redirect-from
