# Site settings
name: Kevin Plattret
email: kevin@plattret.me
url: https://kevinplattret.me
enforce_ssl: kevinplattret.me
twitter_username: kplattret
github_username:  kplattret

# Build settings
markdown: kramdown
exclude:
  - README.md
  - LICENCE.md
  - CNAME
  - assets/css/main.scss
permalink: /post/:title
relative_permalinks: false

# Plugin settings
gems:
  - jekyll-redirect-from
