title: Kevin Plattret
email: kevin@plattret.com
description: Software Engineer
url: https://kevinplattret.com
permalink: /post/:title
exclude:
  - CNAME
  - Gemfile*
  - LICENCE.md
  - README.md
  - assets/css/main.scss
sass:
  style: compressed
github: [metadata]
source_url: https://github.com/kplattret/kevinplattret.com
