title: Kevin Plattret
email: kevin@plattret.me
description: Software Engineer
url: https://kevinplattret.me
permalink: /post/:title
exclude:
  - CNAME
  - Gemfile*
  - LICENCE.md
  - README.md
  - assets/css/main.scss
sass:
  style: compressed
github: [metadata]
plugins:
  - jekyll-redirect-from
