title: Kevin Plattret
description: Software Engineer
email: kevin@plattret.com
url: https://kevinplattret.com
permalink: /post/:title
exclude:
  - Gemfile*
  - README.md
sass:
  style: compressed
source_url: https://github.com/kplattret/kevinplattret.com
